### PR TITLE
Branson memory recorder integration

### PR DESCRIPTION
**Pull request by dmageeLANL**
Memory recorder can be found [on Github](https://github.com/lanl/benchmarks/tree/main/utils/memory_recorder).

Here's what I did:
- Added an option to CMakeLists.txt: USE_MEMORY_RECORD
- This will find Memory Recorder install prefix using MEMORY_RECORD_PREFIX, modulefile environment variable or default prefix. Add lib and include to target directories and library to dependencies.
- Add a #cmakedefine for that option to config.h.in to include header if set.
- Add MemoryRecorder calls around main driver and after the simulation has finished in particle_pass_driver.h, if cmake option is set. 

I was working off the develop branch so in order to merge this into the ats5 branch I also included the memory statistics you put into imc_state.h and the improvements to the README.

### CODE REVIEW

**Comment by dmageeLANL** [comment]
Oh I guess this brings ats5 up to date with develop. Everything else just merged automatically. I can cherry pick it if this isn't the desired effect.

**Comment by alexrlongne** [comment]
I can merge it up to develop as well, I wasn't sure if needed to be frozen at a certain place for those working with it.

**Comment by alexrlongne** [comment]
I've updated the ATS-5 branch to develop. I'm not sure why some of these still look like diffs.

**Comment by dmageeLANL** [comment]
I think it was because your caliper changes just happened to be adjacent to my memory_recorder changes in config.h.in and CmakeLists.txt. It should have figured out the README diff though 🤷‍♂️ . And the imc_state.h was weird too, I don't recall just duplicating an entire 100 lines of code, but who knows.

**Review by alexrlongne — APPROVED** [review]

**Pull request merged**
